# Your .github/workflows/coverity.yml file.
name: Coverity scan

on: [push, pull_request]

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: sudo apt update
    - run: sudo apt-get install --yes erlang-nox python3-pybeam python3-pyelftools python3-rpm
    - uses: vapier/coverity-scan-action@v1
      with:
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        build_language: 'other'
